---
- name: Restart authelia
  community.docker.docker_container:
    name: authelia
    restart: yes

- name: Restart bunkerweb
  community.docker.docker_container:
    name: bunkerweb
    restart: yes

- name: Restart bw-scheduler
  community.docker.docker_container:
    name: bw-scheduler
    restart: yes
